name: Deploy to ECS

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-Login@v1
      with:
        registry: 637423477239.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker build -t medusa-backend .
        docker tag medusa-backend:latest 637423477239.dkr.ecr.ap-south-1.amazonaws.com/medusa-backend:latest
        docker push 637423477239.dkr.ecr.ap-south-1.amazonaws.com/medusa-backend:latest

    # - name: Deploy to ECS
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: medusa-backend-task-def.json
    #     service: medusa-backend-service
    #     cluster: medusa-backend-cluster
    #     container-name: medusa-backend
    #     image: 637423477239.dkr.ecr.ap-south-1.amazonaws.com/medusa-backend:latest
    #     wait-for-service-stability: true
    #     region: ap-south-1
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1
    #     desired-count: 1

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
        working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1